# Generated by Django 4.1.1 on 2022-09-25 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=40)),
                ('is_service', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='outlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlay_name', models.CharField(max_length=50)),
                ('outlay_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_material', to='family.material')),
                ('outlay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_outlay', to='family.outlaytype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlay_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
