# Generated by Django 4.1.1 on 2022-10-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_material_outlaytype_outlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='material_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outlaytype',
            name='user_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='outlaytype_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
